#!/bin/bash
g32() {
    g++ -std=c++17 -Wall -Wextra -Wno-sign-compare \
        -Werror=return-type -fsanitize=address \
        -fsanitize=undefined -fsanitize=bounds \
        -fno-omit-frame-pointer $@
}
g32 -o ../bin/game *.cpp && echo "Compiled successfully." && ../bin/game
